Repository skypyproject/skypy, pull requests merged in 2020-04, with the labels that each got.

#75 SkyPy Driver
  examples/herbel_galaxies.yaml
  scripts/skypy
  setup.cfg
  skypy/core.py
Labels: infrastructure

#67 Galaxy ellipticity distribution from Kacprzak et al. 2109
  docs/galaxy/index.rst
  skypy/galaxy/morphology.py
  skypy/galaxy/tests/test_morphology.py
Labels: enhancement, module: galaxy

#72 sampling haloes
  skypy/halo_sampler.py
Labels: module: nonlinear

#81 Galaxy Sizes
  docs/galaxy/index.rst
  skypy/galaxy/size.py
  skypy/galaxy/tests/test_size.py
Labels: module: galaxy

#51 Camb
  docs/linear/index.rst
  setup.cfg
  skypy/linear/camb.py
  skypy/linear/tests/data/camb_result.txt
  skypy/linear/tests/test_camb.py
Labels: enhancement, module: linear

#83 show documentation warnings in GitHub actions
  .github/problem_matchers/sphinx.json
  .github/workflows/pr.yaml
Labels: documentation, infrastructure

#82 fix and improve galaxy module docs
  docs/galaxy/index.rst
  skypy/galaxy/luminosity.py
  skypy/galaxy/redshift.py
  skypy/galaxy/size.py
  skypy/galaxy/spectrum.py
Labels: documentation, module: galaxy

#80 Setup GitHub apps
  .circleci/config.yml
  README.rst
Labels: documentation, infrastructure

#86 Reparameterized beta distribution for galaxy ellipticities
  docs/galaxy/index.rst
  skypy/galaxy/ellipticity.py
  skypy/galaxy/tests/test_ellipticity.py
Labels: enhancement, module: galaxy

#88 organise GitHub actions
  .circleci/config.yml
  .github/workflows/docs.yaml
  .github/workflows/flake8.yaml
  .github/workflows/pr.yaml
  .github/workflows/tests.yaml
Labels: infrastructure

#90 New restructured halo and power_spectrum modules
  .github/CODEOWNERS
  docs/halo/index.rst
  docs/index.rst
  docs/linear/index.rst
  docs/nonlinear/index.rst
  docs/power_spectrum/index.rst
  setup.cfg
  skypy/halo/__init__.py
  skypy/halo/abundance_matching.py
  skypy/halo/tests/__init__.py
  skypy/halo/tests/test_abundance_matching.py
  skypy/linear/__init__.py
  skypy/nonlinear/__init__.py
  skypy/power_spectrum/__init__.py
  skypy/power_spectrum/camb.py
  skypy/power_spectrum/eisenstein_hu.py
  skypy/power_spectrum/growth.py
  skypy/power_spectrum/halofit.py
  skypy/power_spectrum/tests/__init__.py
  skypy/power_spectrum/tests/data/camb_result.txt
  skypy/power_spectrum/tests/test_camb.py
  skypy/power_spectrum/tests/test_eisenstein_hu.py
  skypy/power_spectrum/tests/test_growth.py
  skypy/power_spectrum/tests/test_halofit.py
Labels: documentation, infrastructure, module: halo, module: linear, module: nonlinear, module: power spectrum

#92 Fix growth_function_carroll doctest with astropy 4.x
  skypy/power_spectrum/growth.py
Labels: bug, module: galaxy

#93 Utils random
  skypy/galaxy/luminosity.py
  skypy/galaxy/tests/test_luminosity.py
  skypy/utils/random.py
  skypy/utils/tests/test_random.py
Labels: infrastructure

#84 Code of Conduct
  .github/CODEOWNERS
  CODE_OF_CONDUCT.md
Labels: documentation

#87 SkyPy Driver
  .github/workflows/tests.yaml
  docs/index.rst
  docs/pipeline/index.rst
  examples/herbel_galaxies.yaml
  scripts/skypy
  setup.cfg
  skypy/pipeline/__init__.py
  skypy/pipeline/driver.py
  skypy/pipeline/tests/__init__.py
  skypy/pipeline/tests/test_driver.py
Labels: infrastructure

#96 Fix kstest in test_schechter using analytic cdf
  skypy/utils/tests/test_random.py
Labels: infrastructure

#94 Press-Schechter Mass Function
  skypy/halo/mass.py
  skypy/halo/tests/test_mass.py
Labels: module: halo

#97 Update references to the default branch
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/docs.yaml
  .github/workflows/flake8.yaml
  .github/workflows/tests.yaml
  CONTRIBUTING.md
Labels: infrastructure

#111 Twine Warning
  setup.cfg
Labels: infrastructure, v0.1 Hack

#118 Add badges for GitHub actions and PyPI
  README.rst
Labels: documentation, v0.1 Hack

#107 Remove some old files
  .travis.yml
  skypy/__init__.py
  skypy/example_mod.py
  skypy/example_subpkg/__init__.py
  skypy/example_subpkg/data/.gitignore
  skypy/example_subpkg/setup_package.py
  skypy/example_subpkg/tests/__init__.py
  skypy/tests/test_example.py
Labels: v0.1 Hack

#112 Fix reference links in growth documentation
  skypy/power_spectrum/growth.py
Labels: documentation, v0.1 Hack

#119 Some fixed typos in the dosctrings.
  skypy/galaxy/luminosity.py
  skypy/galaxy/redshift.py
  skypy/galaxy/spectrum.py
  skypy/galaxy/tests/test_redshift.py
Labels: documentation, v0.1 Hack

#121 Use skypy image in docs build
  docs/Makefile
  images/skypy_image.png
  images/skypy_image.svg
  setup.py
Labels: documentation, v0.1 Hack

#116 updated power spectrum naming convention
  skypy/power_spectrum/camb.py
  skypy/power_spectrum/halofit.py
  skypy/power_spectrum/tests/test_camb.py
  skypy/power_spectrum/tests/test_halofit.py
Labels: module: power spectrum, v0.1 Hack

#109 Fix halo mass documentation
  docs/halo/index.rst
  skypy/halo/mass.py
Labels: documentation, v0.1 Hack

#124 flatten power spectrum hierarchy
  docs/power_spectrum/index.rst
  skypy/power_spectrum/__init__.py
  skypy/power_spectrum/_camb.py
  skypy/power_spectrum/_eisenstein_hu.py
  skypy/power_spectrum/_growth.py
  skypy/power_spectrum/_halofit.py
  skypy/power_spectrum/tests/test_camb.py
  skypy/power_spectrum/tests/test_eisenstein_hu.py
  skypy/power_spectrum/tests/test_growth.py
  skypy/power_spectrum/tests/test_halofit.py
Labels: infrastructure, module: power spectrum

#123 Tidy docs for v0.1
  README.rst
  docs/index.rst
  setup.cfg
Labels: documentation, v0.1 Hack

#126 Docstring for `skypy/init.py`
  skypy/__init__.py
Labels: documentation, v0.1 Hack

#132 Updates for v0.1
  .circleci/config.yml
  .github/workflows/tests.yaml
  .travis.yml
  LICENSE.rst
  README.rst
  docs/_themes/bootstrap-skypy/globaltoc.html
  docs/_themes/bootstrap-skypy/layout.html
  docs/_themes/bootstrap-skypy/localtoc.html
  docs/_themes/bootstrap-skypy/searchbox.html
  docs/_themes/bootstrap-skypy/static/bootstrap-skypy.css
  docs/_themes/bootstrap-skypy/static/copybutton.js
  docs/_themes/bootstrap-skypy/static/sidebar.js
  docs/_themes/bootstrap-skypy/static/skypy_image.ico
  docs/_themes/bootstrap-skypy/static/skypy_image.png
  docs/_themes/bootstrap-skypy/static/skypy_image.svg
  docs/_themes/bootstrap-skypy/static/skypy_text.png
  docs/_themes/bootstrap-skypy/theme.conf
  docs/conf.py
  docs/halo/index.rst
  docs/index.rst
  docs/power_spectrum/index.rst
  docs/utils/index.rst
  licenses/README.rst
  licenses/TEMPLATE_LICENCE.rst
  scripts/skypy
  setup.cfg
  skypy/__init__.py
  skypy/example_mod.py
  skypy/example_subpkg/__init__.py
  skypy/example_subpkg/data/.gitignore
  skypy/example_subpkg/setup_package.py
  skypy/example_subpkg/tests/__init__.py
  skypy/galaxy/luminosity.py
  skypy/galaxy/redshift.py
  skypy/galaxy/size.py
  skypy/galaxy/spectrum.py
  skypy/galaxy/tests/test_redshift.py
  skypy/halo/mass.py
  skypy/power_spectrum/__init__.py
  skypy/power_spectrum/_camb.py
  skypy/power_spectrum/_eisenstein_hu.py
  skypy/power_spectrum/_growth.py
  skypy/power_spectrum/_halofit.py
  skypy/power_spectrum/tests/test_camb.py
  skypy/power_spectrum/tests/test_eisenstein_hu.py
  skypy/power_spectrum/tests/test_growth.py
  skypy/power_spectrum/tests/test_halofit.py
  skypy/tests/test_example.py
  skypy/utils/__init__.py
  skypy/utils/astronomy.py
  skypy/utils/random.py
  skypy/utils/special.py
Labels: infrastructure

#152 Supernova
  docs/index.rst
  docs/supernova/index.rst
  skypy/supernova/__init__.py
Labels: enhancement, module: supernova, v0.2 hack

#156 Initialise gravitational_wave module
  docs/gravitational_wave/index.rst
  docs/index.rst
  skypy/gravitational_wave/__init__.py
Labels: enhancement, module: gravitational wave, v0.2 hack

#161 Add cluster module to documentation index
  docs/cluster/index.rst
  docs/index.rst
Labels: documentation, infrastructure, module: cluster, v0.2 hack

#162 Create test directories for new modules
  skypy/cluster/tests/__init__.py
  skypy/gravitational_wave/tests/__init__.py
  skypy/supernova/tests/__init__.py
Labels: infrastructure, module: cluster, module: gravitational wave, module: supernova, tests, v0.2 hack

#165 fix press_schechter documentation warning
  skypy/halo/mass.py
Labels: bug, documentation

#166 fix driver documentation
  .circleci/config.yml
  .github/workflows/docs.yaml
  docs/pipeline/index.rst
  skypy/pipeline/driver.py
Labels: documentation

#164 improved gammaincc function
  setup.cfg
  skypy/galaxy/redshift.py
  skypy/galaxy/tests/test_luminosity.py
  skypy/utils/random.py
  skypy/utils/special.py
  skypy/utils/tests/data/gammaincc.txt
  skypy/utils/tests/test_random.py
  skypy/utils/tests/test_special.py
Labels: bug, module: utils

#173 Astropy-style skypy driver script
  docs/pipeline/index.rst
  scripts/skypy
  setup.cfg
  skypy/pipeline/scripts/__init__.py
  skypy/pipeline/scripts/skypy.py
  skypy/pipeline/tests/data/cosmology_config.yaml
  skypy/pipeline/tests/data/empty_config.yaml
  skypy/pipeline/tests/test_skypy.py
Labels: build, infrastructure, installation, module: pipeline, release

#169 Astropyify galaxy docs
  docs/galaxy.rst
  docs/galaxy/index.rst
  docs/index.rst
  skypy/galaxy/ellipticity.py
  skypy/galaxy/luminosity.py
  skypy/galaxy/redshift.py
  skypy/galaxy/size.py
  skypy/galaxy/spectrum.py
Labels: documentation
