Repository skypyproject/skypy, pull requests merged in 2021-09, with the labels that each got.

#483 MAINT: Set astropy latest supported version to 4.2
  setup.cfg
Labels: infrastructure, high priority

#477 DOC: Ryden04 ellipticity doc missing section
  skypy/galaxies/morphology.py
Labels: bug, documentation, module: galaxies

#488 MAINT: Update numpy and scipy latest supported versions
  tox.ini
Labels: infrastructure, continuous integration

#485 BUG: Change invalid ecsv datatype from int to uint16
  examples/galaxies/sdss_dered_10deg2.ecsv
Labels: examples

#493 DEV: setuptools==58.0.0
  .readthedocs.yml
  docs/requirements.txt
Labels: external, build, continuous integration, installation, high priority

#487 DOC: Add compatibility workflow badge
  README.rst
Labels: documentation, infrastructure, continuous integration

#491 DEV: Enable pip to install pre-releases in the tox dev environments
  tox.ini
Labels: continuous integration

#489 TST: Use tmp_path fixture for temporary files in unit tests
  skypy/pipeline/tests/test_pipeline.py
  skypy/pipeline/tests/test_skypy.py
Labels: tests

#465 BUG: Move handling of context arguments after handling of .depends keyword
  skypy/pipeline/_pipeline.py
  skypy/pipeline/tests/test_pipeline.py
Labels: bug, module: pipeline

#486 BLD: Set astropy latest supported version to 4.3 and speclite minversion to 0.14
  setup.cfg
  tox.ini
Labels: infrastructure

#494 REV: restore setuptools to latest version on readthedocs
  .readthedocs.yml
  docs/requirements.txt
Labels: continuous integration
