Repository skypyproject/skypy, pull requests merged in 2021-04, with the labels that each got.

#449 DOC: Fix contributor guidelines link
  README.rst
Labels: bug, documentation

#453 ENH: Logging for skypy command line script and Pipeline class
  docs/pipeline/index.rst
  skypy/pipeline/__init__.py
  skypy/pipeline/_items.py
  skypy/pipeline/_pipeline.py
  skypy/pipeline/scripts/skypy.py
  skypy/pipeline/tests/data/test_config.yml
  skypy/pipeline/tests/test_config.py
  skypy/pipeline/tests/test_pipeline.py
  skypy/pipeline/tests/test_skypy.py
Labels: enhancement, infrastructure, module: pipeline

#457 DOC: Describe speclite filters in documentation
  docs/galaxies.rst
  docs/utils/index.rst
Labels: documentation

#463 ENH: Config syntax for importing objects
  examples/galaxies/sdss_photometry.yml
  skypy/pipeline/_config.py
  skypy/pipeline/tests/data/bad_object.yml
  skypy/pipeline/tests/data/test_config.yml
  skypy/pipeline/tests/test_config.py
Labels: enhancement, infrastructure, module: pipeline

#456 DOC: List of Features
  docs/feature_list.rst
  docs/index.rst
Labels: documentation, joss_paper
