Repository skypyproject/skypy, pull requests merged in 2021-11, with the labels that each got.

#501 REV: restore pyparsing to latest version for doc builds
  setup.cfg
Labels: continuous integration

#496 DOC: Update citation file with JOSS paper reference
  CITATION.rst
  docs/index.rst
  docs/project/citation.rst
Labels: documentation, enhancement, high priority, joss_paper

#504 BLD: Set astropy latest supported version to 5.0
  tox.ini
Labels: infrastructure, continuous integration
