Repository skypyproject/skypy, pull requests merged in 2021-06, with the labels that each got.

#454 DOC: How to construct config files
  docs/configuration_files.rst
  docs/index.rst
  docs/luminosity.yml
Labels: documentation, joss_paper

#429 DOC: Remove docstring examples
  CONTRIBUTING.rst
  skypy/galaxies/luminosity.py
  skypy/galaxies/morphology.py
  skypy/galaxies/redshift.py
  skypy/galaxies/spectrum.py
  skypy/utils/random.py
  skypy/utils/special.py
Labels: documentation, examples, infrastructure, tests

#447 DOC: Remove Docstring examples in power_spectrum
  skypy/power_spectrum/_camb.py
  skypy/power_spectrum/_classy.py
  skypy/power_spectrum/_eisenstein_hu.py
  skypy/power_spectrum/_growth.py
  skypy/power_spectrum/_halofit.py
Labels: documentation, examples, module: power spectrum

#460 DOC: Readme updates
  README.rst
Labels: coordinators, documentation

#228 DOC: Expanded landing page documentation
  docs/index.rst
Labels: documentation
