Repository skypyproject/skypy, pull requests merged in 2023-01, with the labels that each got.

#587 MAINT: Replaced whitespace in tox config
  tox.ini
Labels: bug, tests

#589 BLD: Set numpy latest supported version to 1.24
  tox.ini
Labels: continuous integration

#590 BLD: Set scipy latest supported version to 1.10
  tox.ini
Labels: continuous integration

#591 BLD: Set astropy latest supported version to 5.2
  tox.ini
Labels: continuous integration

#588 BLD: Set python latest supported version to 3.11
  .github/workflows/compatibility.yaml
  .github/workflows/tests.yaml
  tox.ini
Labels: continuous integration, compatibility

#596 MAINT: Fix CI for module/halos
  skypy/halos/mass.py
  skypy/halos/tests/test_mass.py
Labels: module: halos, tests, high priority
